name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake
      shell: bash

    - name: Build
      run: |
        mkdir -p build
        cd build
        cmake ..
        make
      working-directory: ./hello-world

    - name: Run Tests
      run: |
        cd build
        ./rectange
      working-directory: ./hello-world
